[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GraphCombinations = "d653b97f-30d3-4d96-b482-58626fc91258"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CairoMakie = "0.15.8"
Documenter = "1.16.1"
GraphMakie = "0.6.3"
GraphRecipes = "0.5.15"
IntervalArithmetic = "< 0.22.32, 1.0"
Literate = "2.21.0"
Plots = "1.41.4"
